FROM node:14-alpine as react-build

RUN mkdir /client
WORKDIR /client
# tsconfig is for typescript lang configuration, needed to describe how packages should run.
COPY ["package.json", "/client/"]

# copy the project files to app
COPY ./ /client/
# cd into app , install packages
RUN cd /client && npm install
# build the project
RUN npm -s run build

# Stage 2, based on Nginx
FROM nginx:1.17.0-alpine
COPY --from=react-build /client/build/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
